import path from "node:path";
import { GitHubClient } from "./github.js";
import { GitRepo } from "./git.js";
import { solveIssue } from "./agent.js";
import { solveIssueWithCodex } from "./codex-agent.js";
import { loadApprovedLessons } from "./lessons.js";
import { c } from "./ui.js";

const log = (...args) => console.log(c.dim(new Date().toISOString()), "-", ...args);

export async function run(opts) {
  const { owner, repo, token } = opts;
  const gh = new GitHubClient(token);

  const me = await gh.me();
  log(`Authenticated as @${me.login}`);

  const upstreamInfo = await gh.repoInfo(owner, repo);
  const base = opts.base || upstreamInfo.default_branch;

  // Decide where we push: the repo itself, or a fork of it.
  let useFork = opts.fork;
  if (!useFork && !(await gh.hasPushAccess(owner, repo))) {
    log(`No push access to ${owner}/${repo} — switching to fork mode.`);
    useFork = true;
  }

  let pushRepo = `${owner}/${repo}`;
  let headOwner = owner;
  if (useFork) {
    log(`Ensuring fork of ${owner}/${repo} exists...`);
    const fork = await gh.ensureFork(owner, repo);
    pushRepo = fork.full_name;
    headOwner = fork.owner.login;
    await gh.syncFork(fork.owner.login, fork.name, base);
    log(`Using fork ${pushRepo}`);
  }

  // Pick the issues to work on.
  let issues;
  if (opts.issues?.length) {
    const all = await gh.listOpenIssues(owner, repo);
    issues = [];
    for (const n of opts.issues) {
      const found = all.find((i) => i.number === n);
      if (!found) {
        log(`Issue #${n} is not an open issue — skipping.`);
        continue;
      }
      issues.push(found);
    }
  } else {
    issues = await gh.listOpenIssues(owner, repo, { labels: opts.labels });
    issues.sort((a, b) => a.number - b.number);
    issues = issues.slice(0, opts.maxIssues);
  }

  if (issues.length === 0) {
    log("No open issues to work on. Done.");
    return [];
  }
  log(`Working on ${issues.length} issue(s): ${issues.map((i) => `#${i.number}`).join(", ")}`);

  // One clone shared by all issues; every issue branches off the fresh base.
  const cloneDir = path.join(opts.workdir, `${owner}-${repo}`);
  log(`Cloning ${pushRepo} into ${cloneDir}...`);
  const git = await GitRepo.clone({
    dir: cloneDir,
    cloneRepo: pushRepo,
    upstream: `${owner}/${repo}`,
    token,
  });
  const startPoint = useFork ? `upstream/${base}` : `origin/${base}`;
  const lessonResult = await loadApprovedLessons(cloneDir);
  for (const warning of lessonResult.warnings) log(`Lesson warning: ${warning}`);
  if (lessonResult.lessons.length > 0) {
    log(`Loaded ${lessonResult.lessons.length} approved repository lesson(s).`);
  }

  const results = [];
  const provider = opts.provider ?? "claude";
  const solve = provider === "codex" ? solveIssueWithCodex : solveIssue;
  for (const issue of issues) {
    const branch = `fixel/issue-${issue.number}`;
    const existing = await gh.findOpenPRByHead(owner, repo, headOwner, branch);
    if (existing) {
      log(`Issue #${issue.number}: open PR already exists (${existing.html_url}) — skipping.`);
      results.push({ issue: issue.number, status: "skipped-existing-pr", pr: existing.html_url });
      continue;
    }

    log(c.bold(c.cyan(`\n=== Issue #${issue.number}: ${issue.title} ===`)));
    await git.checkoutNewBranch(branch, startPoint);

    const comments = await gh.getIssueComments(owner, repo, issue.number);
    let outcome;
    try {
      outcome = await solve({
        repoDir: cloneDir,
        issue,
        comments,
        lessons: lessonResult.lessons,
        model: opts.model,
        onProgress: opts.verbose ? (line) => log(`  ${line}`) : undefined,
      });
    } catch (err) {
      log(`Issue #${issue.number}: agent failed — ${err.message}`);
      results.push({ issue: issue.number, status: "agent-error", error: err.message });
      continue;
    }

    if (!(await git.hasChanges())) {
      log(`Issue #${issue.number}: agent made no file changes — skipping PR.`);
      results.push({ issue: issue.number, status: "no-changes", summary: outcome.summary });
      continue;
    }

    const stat = await git.diffStat();
    log(`Changes:\n${stat}`);

    if (opts.dryRun) {
      log(`Issue #${issue.number}: dry-run — not committing or opening a PR.`);
      await git.run(["reset", "--hard", startPoint]);
      results.push({ issue: issue.number, status: "dry-run", summary: outcome.summary });
      continue;
    }

    await git.commitAll(`Fix #${issue.number}: ${issue.title}`);
    log(`Pushing branch ${branch}...`);
    await git.push(branch);

    const body = [
      `Fixes #${issue.number}`,
      ``,
      outcome.summary || "Automated fix generated by Fixel.",
      ...(lessonResult.lessons.length > 0
        ? [``, `Approved repository lessons available to this run: ${lessonResult.lessons.length}.`]
        : []),
      ``,
      `---`,
      `🔧 *This pull request was generated automatically by [Fixel](https://github.com/AmIrRX0/fixel) using ${provider === "codex" ? "Codex" : "Claude"}.*`,
    ].join("\n");

    const pr = await gh.createPullRequest({
      owner,
      repo,
      title: `Fix #${issue.number}: ${issue.title}`,
      head: useFork ? `${headOwner}:${branch}` : branch,
      base,
      body,
    });
    log(c.green(`✔ Issue #${issue.number}: PR opened → ${pr.html_url}`));
    if (outcome.costUsd != null) log(`  (agent cost: $${outcome.costUsd.toFixed(4)}, turns: ${outcome.numTurns})`);
    results.push({ issue: issue.number, status: "pr-opened", pr: pr.html_url });
  }

  log(c.bold("\n=== Summary ==="));
  for (const r of results) {
    log(`#${r.issue}: ${r.status}${r.pr ? ` (${r.pr})` : ""}`);
  }
  return results;
}
